services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: "NANAOOOO"
        GITHUB_EMAIL: "nanao.shirono@gmail.com"
    container_name: "jupyterlab"
    ports:
      - 8888:8888
    restart: always
    volumes:
      - ./work:/work
    secrets:
      - user_ssh_key

secrets:
  user_ssh_key:
    file: ${SSH_KEY_PATH}